### ISSUE TITLE
[Loadout builder] Cannot lock or exclude items in beta

### ISSUE THREAD

**Issue by rowanbrendan** [DestinyItemManager/DIM#1661]
When I lock items in loadout builder, the builder ignores my selections. Note: this doesn't apply to locking perks.  I can successfully lock those.

(Side note: when selecting perks to lock, the selected items don't show a solid background like they used to, though this seems to just be a graphical error.)

Furthermore, when I exclude items, the item appears to be excluded but displays no icon in the exclude list.  The builder seems to ignore my exclude list as well, accept for the default Memory of Felwinter selection.  Felwinter seems to be ignored and actually shows the correct icon (instead of no icon at all, like the others).

**Comment by bhollis** [comment]
Should be fixed - try again on the website?

**Comment by rowanbrendan** [comment]
What still seems to be missing for me:

1) When dragging an item from the top panel (from, e.g., "Show Hunter gear"), it has one of those "No" signs.  So it won't let me drag items from there to lock them

2) Shift-clicking to exclude items still doesn't show the right icon and the builder doesn't recognize any of these "excluded" items

**Comment by bhollis** [comment]
Hm, I'll admit, I have no idea how to use the advanced features of the loadout builder. Let me get back to you.

**Comment by bhollis** [comment]
OK, I think I have a fix for 1. I don't understand exactly what you're saying for 2 - what do you mean "doesn't recognize", and what icon is supposed to show up?

**Comment by rowanbrendan** [comment]
Seems fixed now, I'll close this.
