### ISSUE TITLE
Unable to connect to Google drive on mobile 

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#2187]
Accepting the popup and nothing happens 😕

**Comment by bhollis** [comment]
I just tried it out in the Simulator and had no problem. let me see what it looks like on a real device.

**Comment by bhollis** [comment]
Hmm, I've been able to link my Google Drive on both app and beta, on an iOS 10.3 iPhone and an iOS 11 iPad.

**Comment by michabbb** [comment]
@bhollis i am using chrome on a galaxy s8+ and when i click on "Login in to Google Drive" i get the popup, that says "if you already....." and if i confirm this, nothing happens....

**Comment by michabbb** [comment]
@bhollis no problem with chrome under windows 10

**Comment by bhollis** [comment]
Pretty sure I fixed this in #2324.

**Comment by michabbb** [comment]
dear @bhollis when will this update be live ??

**Comment by bhollis** [comment]
It went out last week

-Ben

**Comment by michabbb** [comment]
@bhollis so when i look to "about" i see version 4.20.1 and login into google drive is still not working for me (using url: app.dest.....) - am i doing something wrong here ??? thanks !

**Comment by michabbb** [comment]
@bhollis please, this issue is **NOT** finished, why did you close it ????

**Comment by bhollis** [comment]
Don’t worry, I’ll work on it. This is an all volunteer effort and we have real jobs too :-)

**Comment by michabbb** [comment]
@bhollis closing issues that are not fixed has nothing to do with your other things in life, sorry 😕

**Comment by bhollis** [comment]
This is a tough issue, and I thought it was fixed because it worked on the phones I tested. Now I’m realizing that it doesn’t work for some other people, likely because of content blockers and iOS 11 changes that break Google Drive’s scripts. So I reopened it when I got time to revisit the issue. Please be patient.

**Comment by michabbb** [comment]
@bhollis in my case i guess its not a blocker, i am using chrome on android.... don´t see any info that a popup was blocked.... just fyi

**Comment by k20stitch** [comment]
I experienced this issue on an iPad running safari OS 10.3.3

As stated the pop up wasn’t blocked but force killing the app and revisiting it worked. My guess is it was something session based.

**Comment by sdholden** [comment]
Having same issue on chrome for Android on my Samsung tablet.  Drive shows disabled.  Hit login, get popup to confirm.  Press ok, nothing happens other than popup disappears.....Use DIM daily, so this really impacts usefulness....

**Comment by michabbb** [comment]
i am forced to use my pc, because i don´t see my loadouts on mobile, i really hope the developers will find some time to fix this, would be great and i wouldn´t be forced to start my pc everytime i play destiny ;)

**Comment by Wh1rledPeas** [comment]
Same thing happens to me. I'm using Chrome on Android (Google Pixel XL) I tap on [Login to Drive], get a pop-up dialog, tap [okay], dialog disappears, [Login to Drive] is yellow now but at the top it still shows "disabled".

If I get some time (and remember), I'll try to get on my laptop and start up a USB debugging session to see what shows up.

**Comment by bhollis** [comment]
Rolling this into a bigger tracking issue #2713.
