### ISSUE TITLE
DIM not loding

### ISSUE THREAD

**Issue by D2XBOX** [DestinyItemManager/DIM#3731]
I am on Windows 10,  DIM makes it past the Bungie - Xbox authorization and loads to https://app.destinyitemmanager.com/index.html page, then normal title buttons appear briefly, then it goes to a blank screen. Tested on another W 10 machine with same result. Thanks in advance for your help.

**Comment by bhollis** [comment]
Can you open the F12 developer tools and give a screenshot of the console logs?

**Comment by D2XBOX** [comment]
1.
TypeError: Object doesn't support property or method 'finally'
  2.
SCRIPT438: SCRIPT438: Object doesn't support property or method 'finally'
vendors-main-31fb10.js (1,250133)<https://app.destinyitemmanager.com/vendors-main-31fb10.js>
  3.
Transition Rejection($id: 0 type: 6, message: The transition errored, detail: TypeError: Object doesn't support property or method 'finally')
  4.
TypeError: Object doesn't support property or method 'finally' at prototype.addPromise (https://app.destinyitemmanager.com/main-f78205.js:1:11540) at M (https://app.destinyitemmanager.com/main-f78205.js:1:24008) at Generator.prototype.next (native code) at zt.redirectTo (https://app.destinyitemmanager.com/main-f78205.js:1:509725) at Generator.prototype.next (native code) at Ye (https://app.destinyitemmanager.com/vendors-main-31fb10.js:1:160205) at e.prototype.invokeHook (https://app.destinyitemmanager.com/vendors-main-31fb10.js:1:126697) at Anonymous function (https://app.destinyitemmanager.com/vendors-main-31fb10.js:1:126002) at a (https://app.destinyitemmanager.com/vendors-authReturn-main-25b6b8.js:1:33987) at Anonymous function (https://app.destinyitemmanager.com/vendors-authReturn-main-25b6b8.js:1:34134)
  5.
TypeError: Object doesn't support property or method 'finally'
  6.
SCRIPT438: SCRIPT438: Object doesn't support property or method 'finally'
vendors-main-31fb10.js (1,250133)<https://app.destinyitemmanager.com/vendors-main-31fb10.js>
  7.
Transition Rejection($id: 0 type: 6, message: The transition errored, detail: TypeError: Object doesn't support property or method 'finally')
  8.
TypeError: Object doesn't support property or method 'finally' at prototype.addPromise (https://app.destinyitemmanager.com/main-f78205.js:1:11540) at M (https://app.destinyitemmanager.com/main-f78205.js:1:24008) at Generator.prototype.next (native code) at zt.redirectTo (https://app.destinyitemmanager.com/main-f78205.js:1:509725) at Generator.prototype.next (native code) at Ye (https://app.destinyitemmanager.com/vendors-main-31fb10.js:1:160205) at e.prototype.invokeHook (https://app.destinyitemmanager.com/vendors-main-31fb10.js:1:126697) at Anonymous function (https://app.destinyitemmanager.com/vendors-main-31fb10.js:1:126002) at a (https://app.destinyitemmanager.com/vendors-authReturn-main-25b6b8.js:1:33987) at Anonymous function (https://app.destinyitemmanager.com/vendors-authReturn-main-25b6b8.js:1:34134)
  9.
TypeError: Object doesn't support property or method 'finally'
  10.
SCRIPT438: SCRIPT438: Object doesn't support property or method 'finally'
vendors-main-31fb10.js (1,250133)<https://app.destinyitemmanager.com/vendors-main-31fb10.js>


________________________________

**Comment by JT-IT** [comment]
I'm getting the exact same error, also in Edge, also Windows 10.  Don't see any updates installed in event log other than Defender defs.

**Comment by bhollis** [comment]
Just pushed a fix out - let me know if it's working for you now.

**Comment by D2XBOX** [comment]
Did not fix for me. I did a google search on " Object doesn't support property or method 'finally' " and got this link
https://stackoverflow.com/questions/50096031/typeerror-object-doesnt-support-property-or-method-finally  . Not sure if the information helps but it seemed to have a solution to a similar problem.

thanks again

________________________________

**Comment by bhollis** [comment]
Can you clear your cache and try again?

**Comment by D2XBOX** [comment]
Same result.

________________________________

**Comment by bhollis** [comment]
OK, I pushed another update to beta. Any luck?

**Comment by D2XBOX** [comment]
The beta has one more button labeled " report bug " in the menu bar at the top, but other than that it loads then goes to blank screen with the same error in the console as the main site.

________________________________

**Comment by Bubblicus** [comment]
Here is what I'm getting:

![5](https://user-images.githubusercontent.com/49430029/55779702-0b27c880-5a9e-11e9-876c-f9eb64b3f6e0.PNG)

**Comment by bhollis** [comment]
Try now?

**Comment by Bubblicus** [comment]
Still not working on Edge. It is working on Chrome, so I will just continue using DIM on there.

**Comment by D2XBOX** [comment]
Beta works, Alpha did not. Cleared cache for both.

________________________________

**Comment by bhollis** [comment]
OK. I'm pushing my fix out to app now.

**Comment by D2XBOX** [comment]
TYVM for the fast fix.

________________________________
